INSERT INTO public.catalog_service (id, name, category_id) VALUES (1, 'Ремонт бензиновых двигателей', 2);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (2, 'Ремонт дизельных двигателей', 2);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (3, 'Ремонт топливной аппаратуры дизельных двигателей', 2);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (4, 'Ремонт выхлопных систем', 2);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (5, 'Ремонт карбюраторов / инжекторов', 2);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (6, 'Ремонт АКПП', 3);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (7, 'Ремонт МКПП', 3);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (8, 'Развал / Схождение', 4);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (9, 'Ремонт ходовой части автомобиля', 4);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (10, 'Кузовной ремонт', 5);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (11, 'Антикоррозийная обработка автомобилей', 5);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (12, 'Ремонт автоэлектрики', 6);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (13, 'Компьютерная диагностика автомобилей', 6);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (14, 'Ремонт / обслуживание климатических систем автомобиля', 6);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (15, 'Автосигнализации', 6);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (16, 'Установка / ремонт автомобильной оптики', 6);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (17, 'Установка / ремонт автостёкол', 7);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (18, 'Технический осмотр транспорта', 7);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (19, 'Аппаратная замена масла', 7);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (20, 'Тонирование автостёкол', 8);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (21, 'Тюнинг', 8);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (22, 'Газовое оборудование для автотранспорта', 9);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (23, 'Автоматическая мойка', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (24, 'Бесконтактная мойка', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (25, 'Ручная мойка', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (26, 'Химчистка', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (27, 'Мойка двигателя', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (28, 'Защитная полировка', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (29, 'Мойка днища', 10);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (30, 'Выездной шиномонтаж', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (31, 'Грузовой шиномонтаж', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (32, 'Балансировка', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (33, 'Ремонт дисков', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (34, 'Ремонт шин', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (35, 'Хранение шин', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (36, 'Для мототехники', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (37, 'Ошиповка', 18);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (38, 'Многоуровневые', 27);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (39, 'Надземные', 27);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (40, 'Подземные', 27);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (41, 'Стоянки для инвалидов', 27);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (42, 'ДТ', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (43, '80', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (44, '92', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (45, '95', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (46, '98', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (47, 'пропан', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (48, 'метан', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (49, 'станция зарядки электротранспорта', 32);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (50, 'Автозапчасти для легковых автомобилей', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (51, 'Автозапчасти для грузовых автомобилей', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (52, 'Контрактные автозапчасти', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (53, 'Запчасти для общественного транспорта', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (54, 'Запчасти для спецтехники', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (55, 'Автоаксессуары', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (56, 'Шины / Диски', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (57, 'Автомасла / Мотомасла / Химия', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (58, 'Автозвук', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (59, 'Автомобильные аккумуляторы', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (60, 'Специализированное автооборудование', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (61, 'Автостекло', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (62, 'Автоэмали', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (63, 'Запчасти для мототехники', 41);
INSERT INTO public.catalog_service (id, name, category_id) VALUES (64, 'Тонировочные / защитные плёнки для автомобилей', 41);